FROM rocker/tidyverse:4.4.3

RUN apt-get update \
    && apt-get install -y --no-install-recommends libcurl4-openssl-dev libarchive-dev \
    && rm -rf /var/lib/apt/lists/* \
    && install2.r DT duckdb factoextra GGally ggpubR ggVennDiagram httpuv leaflet shinyBS shinylive shinyjs shinyWidgets

COPY app/ /home/rstudio/resfor-shiny/app
# COPY data/ /home/rstudio/resfor-shiny/data

COPY rsession.conf /etc/rstudio/rsession.conf

WORKDIR /home/rstudio/resfor-shiny/app

RUN chown --recursive rstudio:rstudio /home/rstudio/resfor-shiny
