name: Build

# Workflow conditions
on:
  push:
    branches:
      - '*'
  release:
    types: [published]

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  IMAGE_NAME: "bff-afirms/resfor-shiny:latest"

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_NAME }}

      # # Extract site from container
      # - name: Extract
      #   run: |
      #     id=$(docker create ${{ env.IMAGE_NAME }})
      #     docker cp $id:/srv/shiny-server/docs ./site
      #     docker container rm -v $id

      # # Upload artifact for debugging
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: website
      #     path: site/
      #     retention-days: 1
      #     if-no-files-found: error
      
      # # Deploy to pages site
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     folder: site