name: Build

# Workflow conditions
on:
  push:
    branches:
      - 'main'
  release:
    types: [published]

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test
        run: |
          docker run --entrypoint bash ${{ env.IMAGE_NAME }} -c "echo test"
  
      # # Upload a tar file that will work with GitHub Pages
      # # Make sure to set a retention day to avoid running into a cap
      # # This artifact shouldn't be required after deployment onto pages was a success.
      # - name: Upload Pages artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with: 
      #     retention-days: 1
      
      # # Use an Action deploy to push the artifact onto GitHub Pages
      # # This requires the `Action` tab being structured to allow for deployment
      # # instead of using `docs/` or the `gh-pages` branch of the repository
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4